name: Update Porter App
description: Update Porter App
inputs:
  app:
    description: name of application
    required: true
  cluster:
    description: cluster ID of Porter cluster
    required: true
  dockerfile:
    description: path to the dockerfile used to build the application
    required: false
  host:
    description: host URL of Porter instance
    required: false
  namespace:
    description: namespace for the application
    required: false
    default: default
  path:
    description: path to build directory
    required: false
  project:
    description: project ID of Porter project
    required: true
  token:
    description: token for Porter authentication
    required: true
  build_secrets:
    description: Comma-separated list of key=value pairs for build secrets
    required: false
  tag:
    description: tag for the created image
    required: false
    default: latest
runs:
  using: docker
  image: Dockerfile
branding:
  color: purple
  icon: upload-cloud
